# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./compiled-docs/
exclude:          [".gitignore"]
port:             9002
baseurl:          /floatThead/

# Site vars
base_url:         "/floatThead"

js_url:           http://mkoryak.github.io/floatThead/dist/jquery.floatThead.min.js
